---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    kubernetes.io/metadata.name: operators
    name: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-agent-operator
  namespace: operators
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: wazuh-agent-operator
    namespace: operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-agent-operator
  namespace: operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-agent-operator
  namespace: operators
spec:
  replicas: 1  # do not change to >1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  wazuh-agent-operator
  template:
    metadata:
      labels:
        app: wazuh-agent-operator
    spec:
      serviceAccountName: wazuh-agent-operator
      containers:
        - name: operator
          image: opennix/wazuh-agent-kubernetes-operator
          imagePullPolicy: IfNotPresent
